#!/usr/bin/env bash
set -euo pipefail

REPO="kiry163/filehub"
GH_API="https://api.github.com/repos/${REPO}"
GH_RAW_BASE="https://raw.githubusercontent.com/${REPO}"
GH_RELEASE_BASE="https://github.com/${REPO}/releases/download"
IMAGE="ghcr.io/${REPO}"

DEFAULT_DIR="${HOME}/.filehub"
DEFAULT_PORT="8080"
DEFAULT_MINIO_PORT="9000"
DEFAULT_MINIO_CONSOLE_PORT="9001"

usage() {
  cat <<'EOF'
FileHub one-click installer (Docker + CLI)

Usage:
  curl -fsSL https://raw.githubusercontent.com/kiry163/filehub/main/scripts/install.sh | bash

Options:
  --dir <path>              Install directory (default: ~/.filehub)
  --port <port>             FileHub port on host (default: 8080)
  --minio-port <port>       MinIO port on host (default: 9000)
  --minio-console-port <p>  MinIO console port on host (default: 9001)
  --public-endpoint <url>   Public UI base URL (default: auto-detect)
  --version <tag>           Release tag to install (default: latest)
  --help                    Show this help
EOF
}

log() { printf '%s\n' "$*"; }
die() { printf 'Error: %s\n' "$*" >&2; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

http_get() {
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$1"
    return
  fi
  if command -v wget >/dev/null 2>&1; then
    wget -qO- "$1"
    return
  fi
  die "need curl or wget"
}

rand_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
    return
  fi
  tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32
}

compose_cmd() {
  if docker compose version >/dev/null 2>&1; then
    echo "docker compose"
    return
  fi
  if command -v docker-compose >/dev/null 2>&1; then
    echo "docker-compose"
    return
  fi
  die "docker compose not found (need docker compose plugin or docker-compose)"
}

latest_version() {
  # Returns tag_name from GitHub releases/latest
  local json
  json="$(http_get "${GH_API}/releases/latest")" || return 1
  printf '%s' "$json" | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1
}

fetch_public_ip() {
  # Uses https://api.ip.sb/jsonip and returns IP string.
  local json ip
  json="$(http_get "https://api.ip.sb/jsonip")" || return 1
  ip="$(printf '%s' "$json" | sed -n 's/.*"ip"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1)"
  [[ -n "$ip" ]] || return 1
  printf '%s' "$ip"
}

write_filehub_config() {
  local path="$1"
  local jwt_secret="$2"
  local admin_password="$3"
  local local_key="$4"
  local minio_user="$5"
  local minio_pass="$6"

  cat >"$path" <<EOF
# Generated by FileHub installer
server:
  port: 8080
  log_level: info

database:
  path: ./data/filehub.db

auth:
  jwt_secret: "${jwt_secret}"
  jwt_expire_hours: 24
  refresh_expire_days: 7
  admin_username: admin
  admin_password: "${admin_password}"
  local_key: "${local_key}"

upload:
  max_size_mb: 1024

minio:
  endpoint: minio:9000
  access_key: "${minio_user}"
  secret_key: "${minio_pass}"
  bucket: filehub
  use_ssl: false
  region: ""
EOF
}

write_compose() {
  local path="$1"
  local version="$2"
  local port="$3"
  local minio_port="$4"
  local minio_console_port="$5"
  local minio_user="$6"
  local minio_pass="$7"

  cat >"$path" <<EOF
services:
  minio:
    image: minio/minio:latest
    container_name: filehub-minio
    command: server /data --console-address ":9001"
    ports:
      - "${minio_port}:9000"
      - "${minio_console_port}:9001"
    environment:
      MINIO_ROOT_USER: ${minio_user}
      MINIO_ROOT_PASSWORD: ${minio_pass}
    volumes:
      - ./data/minio:/data

  filehub:
    image: ${IMAGE}:${version}
    container_name: filehub
    depends_on:
      - minio
    ports:
      - "${port}:8080"
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro
    working_dir: /app
EOF
}

install_cli() {
  local version="$1"
  local dest_dir="$2"

  mkdir -p "$dest_dir"
  local url="${GH_RELEASE_BASE}/${version}/filehub-cli-linux-amd64"
  log "Downloading filehub-cli: ${url}"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$url" -o "${dest_dir}/filehub-cli"
  else
    wget -qO "${dest_dir}/filehub-cli" "$url"
  fi
  chmod +x "${dest_dir}/filehub-cli"
}

init_cli_config() {
  local cli_bin="$1"
  local port="$2"
  local public_endpoint="$3"
  local local_key="$4"

  "$cli_bin" config init \
    --endpoint "http://localhost:${port}" \
    --public-endpoint "${public_endpoint}" \
    --local-key "${local_key}" >/dev/null
}

main() {
  local install_dir="$DEFAULT_DIR"
  local port="$DEFAULT_PORT"
  local minio_port="$DEFAULT_MINIO_PORT"
  local minio_console_port="$DEFAULT_MINIO_CONSOLE_PORT"
  local public_endpoint=""
  local version=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dir)
        install_dir="$2"; shift 2 ;;
      --port)
        port="$2"; shift 2 ;;
      --minio-port)
        minio_port="$2"; shift 2 ;;
      --minio-console-port)
        minio_console_port="$2"; shift 2 ;;
      --public-endpoint)
        public_endpoint="$2"; shift 2 ;;
      --version)
        version="$2"; shift 2 ;;
      --help|-h)
        usage; exit 0 ;;
      *)
        die "unknown argument: $1" ;;
    esac
  done

  need_cmd docker
  local compose
  compose="$(compose_cmd)"

  if [[ -z "$version" ]]; then
    log "Resolving latest version from GitHub releases..."
    version="$(latest_version)"
    [[ -n "$version" ]] || die "failed to resolve latest release tag; try --version vX.Y.Z"
  fi

  mkdir -p "$install_dir/data/minio"
  cd "$install_dir"

  local jwt_secret admin_password local_key minio_user minio_pass
  jwt_secret="$(rand_token)$(rand_token)"
  admin_password="$(rand_token)"
  local_key="$(rand_token)"
  minio_user="minioadmin"
  minio_pass="$(rand_token)"

  write_filehub_config "${install_dir}/config.yaml" "$jwt_secret" "$admin_password" "$local_key" "$minio_user" "$minio_pass"
  write_compose "${install_dir}/docker-compose.yml" "$version" "$port" "$minio_port" "$minio_console_port" "$minio_user" "$minio_pass"

  if [[ -z "$public_endpoint" ]]; then
    if ip="$(fetch_public_ip 2>/dev/null)"; then
      public_endpoint="http://${ip}:${port}"
    else
      public_endpoint="http://localhost:${port}"
    fi
  fi

  log "Pulling images..."
  docker pull "${IMAGE}:${version}" >/dev/null
  docker pull "minio/minio:latest" >/dev/null

  log "Starting services..."
  ${compose} -f "${install_dir}/docker-compose.yml" up -d

  local cli_dir="${HOME}/.local/bin"
  install_cli "$version" "$cli_dir"
  init_cli_config "${cli_dir}/filehub-cli" "$port" "$public_endpoint" "$local_key"

  log ""
  log "Installed FileHub ${version}"
  log "- UI:         http://localhost:${port}"
  log "- Public UI:  ${public_endpoint}"
  log "- API:        http://localhost:${port}/api/v1"
  log "- MinIO:      http://localhost:${minio_port}"
  log "- MinIO UI:   http://localhost:${minio_console_port}"
  log ""
  log "Credentials (save these now):"
  log "- admin username: admin"
  log "- admin password: ${admin_password}"
  log "- local_key:      ${local_key}"
  log ""
  log "CLI: ${cli_dir}/filehub-cli"
  if [[ ":$PATH:" != *":${cli_dir}:"* ]]; then
    log "Note: add to PATH: export PATH=\"${cli_dir}:\$PATH\""
  fi
  log ""
  log "Manage services: cd ${install_dir} && ${compose} up -d | ${compose} down"
}

main "$@"
